apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: kpack-builder
  namespace: ncc-dev
spec:
  serviceAccountName: kpack-service-account
  tag: harbor.fintech23.xyz/core/test-builder:test
  stack:
    name: default-base
    kind: ClusterStack
  store:
    name: default-clusterstore
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs