apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: ncc-dev
secrets:
  - name: harbor-registry
  - name: gitea-secret
imagePullSecrets:
  - name: harbor-registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-cluster-admin
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - secrets
      - configmaps
      - endpoints
      - replicaSets
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - watch
      - delete

  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - watch

  - apiGroups: ["apps"] 
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - watch
      - delete

  - apiGroups: ["networking.k8s.io"] 
    resources:
      - ingresses
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - watch
      - delete


  - apiGroups: ["kpack.io"]
    resources:
      - builds
      - images
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - watch
      - delete
      
  - apiGroups: ["argoproj.io"]
    resources:
      - workflows
      - clusterworkflowtemplates
      - workflowtemplates
      - workflowtaskresults
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-service-account-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: kpack-service-account
    namespace: ncc-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kpack-cluster-admin

